// Mock data for development

import type { Product, Category, DashboardStats, RevenueData } from "./types"

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Pickles",
    slug: "pickles",
    description: "Traditional and exotic pickle varieties",
    image: "/pickle-jar.jpg",
    productCount: 12,
    order: 1,
    isActive: true,
  },
  {
    id: "2",
    name: "Red Chilli",
    slug: "red-chilli",
    description: "Spicy red chilli products",
    image: "/red-chilli.jpg",
    productCount: 8,
    order: 2,
    isActive: true,
  },
  {
    id: "3",
    name: "Mango",
    slug: "mango",
    description: "Sweet and tangy mango preserves",
    image: "/mango-pickle.jpg",
    productCount: 6,
    order: 3,
    isActive: true,
  },
  {
    id: "4",
    name: "Green Chilli",
    slug: "green-chilli",
    description: "Fresh green chilli pickles",
    image: "/green-chilli.jpg",
    productCount: 5,
    order: 4,
    isActive: true,
  },
  {
    id: "5",
    name: "Garlic",
    slug: "garlic",
    description: "Aromatic garlic preserves",
    image: "/garlic-pickle.jpg",
    productCount: 4,
    order: 5,
    isActive: true,
  },
  {
    id: "6",
    name: "Mixed",
    slug: "mixed",
    description: "Delicious mixed vegetable pickles",
    image: "/mixed-pickle.jpg",
    productCount: 7,
    order: 6,
    isActive: true,
  },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Mango Pickle",
    slug: "mango-pickle",
    description:
      "A tangy & spicy Mango made with a combination of a lot of spices of Mango, Garlic, Ginger, Chilli, Turmeric, Fenugreek, Mustard, Asafoetida, Salt, and Oil.",
    price: 449,
    compareAtPrice: 599,
    images: ["/mango-pickle-jar.png", "/mango-pickle-close-up.jpg"],
    category: "Mango",
    categoryId: "3",
    weight: ["200g", "400g", "800g"],
    inStock: true,
    stockQuantity: 50,
    rating: 4.5,
    reviewCount: 128,
    isFeatured: true,
    isBestSeller: true,
    isOnSale: true,
    tags: ["spicy", "traditional", "bestseller"],
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Red Chilli Pickle",
    slug: "red-chilli-pickle",
    description: "Fiery red chilli pickle made with premium red chillies and aromatic spices.",
    price: 399,
    compareAtPrice: 499,
    images: ["/red-chilli.jpg"],
    category: "Red Chilli",
    categoryId: "2",
    weight: ["200g", "400g"],
    inStock: true,
    stockQuantity: 35,
    rating: 4.3,
    reviewCount: 89,
    isFeatured: false,
    isBestSeller: true,
    isOnSale: true,
    tags: ["spicy", "hot"],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
  },
  {
    id: "3",
    name: "Green Chilli Pickle",
    slug: "green-chilli-pickle",
    description: "Fresh green chilli pickle with a perfect balance of heat and tanginess.",
    price: 379,
    images: ["/green-chilli.jpg"],
    category: "Green Chilli",
    categoryId: "4",
    weight: ["200g", "400g"],
    inStock: true,
    stockQuantity: 42,
    rating: 4.6,
    reviewCount: 95,
    isFeatured: true,
    isBestSeller: false,
    isOnSale: false,
    tags: ["spicy", "fresh"],
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
  },
  {
    id: "4",
    name: "Garlic Pickle",
    slug: "garlic-pickle",
    description: "Aromatic garlic pickle with a rich blend of traditional spices.",
    price: 429,
    images: ["/garlic-pickle.jpg"],
    category: "Garlic",
    categoryId: "5",
    weight: ["200g", "400g"],
    inStock: true,
    stockQuantity: 28,
    rating: 4.4,
    reviewCount: 76,
    isFeatured: false,
    isBestSeller: false,
    isOnSale: false,
    tags: ["aromatic", "traditional"],
    createdAt: "2024-01-08",
    updatedAt: "2024-01-08",
  },
]

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalRevenue: 125430,
  totalOrders: 1234,
  totalCustomers: 856,
  totalProducts: 48,
  revenueChange: 12.5,
  ordersChange: 8.3,
  customersChange: 15.2,
  productsChange: 4.1,
}

export const MOCK_REVENUE_DATA: RevenueData[] = [
  { month: "Jan", revenue: 12500, orders: 145 },
  { month: "Feb", revenue: 15200, orders: 178 },
  { month: "Mar", revenue: 18900, orders: 210 },
  { month: "Apr", revenue: 16700, orders: 195 },
  { month: "May", revenue: 21300, orders: 245 },
  { month: "Jun", revenue: 19800, orders: 228 },
]

export const SHIPPING_COST = 50
export const TAX_RATE = 0.08
export const FREE_SHIPPING_THRESHOLD = 999
